services:
  app:
    build:
      context: .
      target: app
      args:
        VITE_API_URL: ${VITE_API_URL}
    expose:
      - "3001"
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"


  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always


  flyway:
    build:
      context: .
      target: flyway
    environment:
      FLYWAY_URL: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
      FLYWAY_VALIDATE_MIGRATION_NAMING: "true"
    command: migrate
    extra_hosts:
    - "host.docker.internal:host-gateway"



volumes:
  caddy_data:
  caddy_config: