services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file:
      - .env
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy
    restart: always

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always


  # mysql:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DB}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10


  # redis:
  #   image: redis:7
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  flyway:
    image: flyway/flyway
    env_file:
    - .env
    command: >
      -url=jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}
      -user=${MYSQL_USER}
      -password=${MYSQL_PASSWORD}
      migrate
    volumes:
      - ./flyway/sql:/flyway/sql
      # - ./backend/flyway/sql:/flyway/sql



volumes:
  # mysql_data:
  caddy_data:
  caddy_config: