services:
  app:
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --legacy-watch
    environment:
      NODE_ENV: development

  # mysql:
  #   ports:
  #     - "3307:3306"

  # redis:
  #   ports:
  #     - "6379:6379"