services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy

  # mysql:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DB}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10


  # redis:
  #   image: redis:7
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  flyway:
    image: flyway/flyway
    command: >
      -url=jdbc:mysql://host.docker.internal:3306/${MYSQL_DB}
      -user=${MYSQL_USER}
      -password=${MYSQL_PASSWORD}
      migrate
    volumes:
      - ./flyway/sql:/flyway/sql


# volumes:
#   mysql_data: