services:
  app:
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development

  mysql:
    ports:
      - "3307:3306"

  redis:
    ports:
      - "6379:6379"