CREATE TABLE users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  display_name VARCHAR(30) NOT NULL,
  username VARCHAR(30) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  publicKey VARCHAR(255) NOT NULL,
  google_id VARCHAR(100) UNIQUE
);

ALTER TABLE USERS DROP COLUMN google_id, MODIFY publicKey VARCHAR(255);
